name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Use Node.js 20
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Configure GitHub Pages (for static site generators)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      # Step 4: Install dependencies
      - run: npm install

      # Step 5: Build the site
      - run: npm run build

      # Step 6: Upload build artifacts for GitHub Pages
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./out"

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
