name: Build, Test, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Step 1: Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: /Users/imac/IdeaProjects/CicdTest/node_modules install

      - name: Build the project
        run: npm run build
             npm run export  # This generates the 'out' directory

  # Step 2: Test job
  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Run Tests
        run: mvn clean test -PloginpageTest

  # Step 3: Deploy job
  deploy:
    needs: test  # This job depends on the test job
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Upload build artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
