# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello Git"
